name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_cli:
    name: Build Create Rindo CLI
    uses: ./.github/workflows/build.yml

  format:
    name: Format Check
    uses: ./.github/workflows/format.yml

  smoke_test:
    name: Smoke Testing
    needs: [build_cli]
    uses: ./.github/workflows/test-component-starter.yml
